// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "/wails/runtime.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as qrengine$0 from "../qrengine/models.js";

export class HistoryEntry {
    "id": string;
    "kind": Kind;
    "content": string;
    "content_type": qrengine$0.ContentType;
    "timestamp": string;
    "pinned": boolean;
    "source"?: string;
    "error_level"?: string;
    "style"?: StyleOptions | null;
    "meta"?: { [_ in string]?: any };

    /** Creates a new HistoryEntry instance. */
    constructor($$source: Partial<HistoryEntry> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = Kind.$zero;
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }
        if (!("content_type" in $$source)) {
            this["content_type"] = qrengine$0.ContentType.$zero;
        }
        if (!("timestamp" in $$source)) {
            this["timestamp"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("pinned" in $$source)) {
            this["pinned"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HistoryEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): HistoryEntry {
        const $$createField8_0 = $$createType1;
        const $$createField9_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("style" in $$parsedSource) {
            $$parsedSource["style"] = $$createField8_0($$parsedSource["style"]);
        }
        if ("meta" in $$parsedSource) {
            $$parsedSource["meta"] = $$createField9_0($$parsedSource["meta"]);
        }
        return new HistoryEntry($$parsedSource as Partial<HistoryEntry>);
    }
}

export enum Kind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    KindScan = "scan",
    KindGenerate = "generate",
};

export class Preset {
    "name": string;
    "style": StyleOptions;

    /** Creates a new Preset instance. */
    constructor($$source: Partial<Preset> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("style" in $$source)) {
            this["style"] = (new StyleOptions());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Preset instance from a string or object.
     */
    static createFrom($$source: any = {}): Preset {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("style" in $$parsedSource) {
            $$parsedSource["style"] = $$createField1_0($$parsedSource["style"]);
        }
        return new Preset($$parsedSource as Partial<Preset>);
    }
}

export class Settings {
    "theme": string;
    "default_format": string;
    "default_ecc": string;
    "language": string;
    "size": number;
    "margin": number;
    "shape": string;
    "check_url_safety": boolean;
    "last_window"?: WindowPos | null;
    "presets": Preset[];

    /** Creates a new Settings instance. */
    constructor($$source: Partial<Settings> = {}) {
        if (!("theme" in $$source)) {
            this["theme"] = "";
        }
        if (!("default_format" in $$source)) {
            this["default_format"] = "";
        }
        if (!("default_ecc" in $$source)) {
            this["default_ecc"] = "";
        }
        if (!("language" in $$source)) {
            this["language"] = "";
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }
        if (!("margin" in $$source)) {
            this["margin"] = 0;
        }
        if (!("shape" in $$source)) {
            this["shape"] = "";
        }
        if (!("check_url_safety" in $$source)) {
            this["check_url_safety"] = false;
        }
        if (!("presets" in $$source)) {
            this["presets"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Settings instance from a string or object.
     */
    static createFrom($$source: any = {}): Settings {
        const $$createField8_0 = $$createType4;
        const $$createField9_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("last_window" in $$parsedSource) {
            $$parsedSource["last_window"] = $$createField8_0($$parsedSource["last_window"]);
        }
        if ("presets" in $$parsedSource) {
            $$parsedSource["presets"] = $$createField9_0($$parsedSource["presets"]);
        }
        return new Settings($$parsedSource as Partial<Settings>);
    }
}

export class StyleOptions {
    "format": string;
    "ecc": string;
    "fg_color": string;
    "bg_color": string;
    "shape": string;
    "size": number;
    "margin": number;
    "logo_b64"?: string;

    /** Creates a new StyleOptions instance. */
    constructor($$source: Partial<StyleOptions> = {}) {
        if (!("format" in $$source)) {
            this["format"] = "";
        }
        if (!("ecc" in $$source)) {
            this["ecc"] = "";
        }
        if (!("fg_color" in $$source)) {
            this["fg_color"] = "";
        }
        if (!("bg_color" in $$source)) {
            this["bg_color"] = "";
        }
        if (!("shape" in $$source)) {
            this["shape"] = "";
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }
        if (!("margin" in $$source)) {
            this["margin"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StyleOptions instance from a string or object.
     */
    static createFrom($$source: any = {}): StyleOptions {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StyleOptions($$parsedSource as Partial<StyleOptions>);
    }
}

export class WindowPos {
    "x": number;
    "y": number;
    "w": number;
    "h": number;

    /** Creates a new WindowPos instance. */
    constructor($$source: Partial<WindowPos> = {}) {
        if (!("x" in $$source)) {
            this["x"] = 0;
        }
        if (!("y" in $$source)) {
            this["y"] = 0;
        }
        if (!("w" in $$source)) {
            this["w"] = 0;
        }
        if (!("h" in $$source)) {
            this["h"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WindowPos instance from a string or object.
     */
    static createFrom($$source: any = {}): WindowPos {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WindowPos($$parsedSource as Partial<WindowPos>);
    }
}

// Private type creation functions
const $$createType0 = StyleOptions.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Map($Create.Any, $Create.Any);
const $$createType3 = WindowPos.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = Preset.createFrom;
const $$createType6 = $Create.Array($$createType5);
