// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "/wails/runtime.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as qrengine$0 from "../qrengine/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AddHistory(entry: $models.HistoryEntry): $CancellablePromise<$models.HistoryEntry> {
    return $Call.ByID(603619408, entry).then(($result: any) => {
        return $$createType0($result);
    });
}

export function AppVersion(): $CancellablePromise<string> {
    return $Call.ByID(431824860);
}

export function AssessURLSecurity(rawURL: string): $CancellablePromise<qrengine$0.SafetyAssessment> {
    return $Call.ByID(4293230062, rawURL).then(($result: any) => {
        return $$createType1($result);
    });
}

export function BuildContent(req: qrengine$0.BuildContentRequest): $CancellablePromise<string> {
    return $Call.ByID(676069464, req);
}

export function ClearHistory(kind: string): $CancellablePromise<void> {
    return $Call.ByID(1227201166, kind);
}

export function CompleteTask(result: string): $CancellablePromise<void> {
    return $Call.ByID(3026474227, result);
}

export function DecodeBase64(imageData: string, multiScan: boolean): $CancellablePromise<qrengine$0.ScanResponse> {
    return $Call.ByID(1877736532, imageData, multiScan).then(($result: any) => {
        return $$createType2($result);
    });
}

export function DecodeFile(path: string, multiScan: boolean): $CancellablePromise<qrengine$0.ScanResponse> {
    return $Call.ByID(2689686493, path, multiScan).then(($result: any) => {
        return $$createType2($result);
    });
}

export function DeleteHistory(id: string): $CancellablePromise<void> {
    return $Call.ByID(3905524878, id);
}

export function DeletePreset(name: string): $CancellablePromise<$models.Preset[]> {
    return $Call.ByID(91976149, name).then(($result: any) => {
        return $$createType4($result);
    });
}

export function DetectContentType(content: string): $CancellablePromise<string> {
    return $Call.ByID(2117000687, content);
}

export function GenerateBase64(opts: qrengine$0.EncodeOptions): $CancellablePromise<string> {
    return $Call.ByID(3305710161, opts);
}

export function GenerateWithWarnings(opts: qrengine$0.EncodeOptions): $CancellablePromise<[string, string[]]> {
    return $Call.ByID(198374367, opts).then(($result: any) => {
        $result[1] = $$createType5($result[1]);
        return $result;
    });
}

export function GetSettings(): $CancellablePromise<$models.Settings> {
    return $Call.ByID(3023222958).then(($result: any) => {
        return $$createType6($result);
    });
}

export function GetWorkerPayload(): $CancellablePromise<string> {
    return $Call.ByID(135457625);
}

export function ListHistory(): $CancellablePromise<$models.HistoryEntry[]> {
    return $Call.ByID(2054176679).then(($result: any) => {
        return $$createType7($result);
    });
}

export function ListPresets(): $CancellablePromise<$models.Preset[]> {
    return $Call.ByID(1048547839).then(($result: any) => {
        return $$createType4($result);
    });
}

export function OpenURL(url: string): $CancellablePromise<void> {
    return $Call.ByID(575055286, url);
}

export function ProcessBatchGUI(batchPath: string, opts: qrengine$0.EncodeOptions): $CancellablePromise<[string, number]> {
    return $Call.ByID(4625437, batchPath, opts);
}

export function RegenerateFromHistory(id: string): $CancellablePromise<string> {
    return $Call.ByID(6104177, id);
}

export function SaveDataURL(dataURL: string, suggestedName: string): $CancellablePromise<string> {
    return $Call.ByID(478621029, dataURL, suggestedName);
}

export function SaveSettings(settings: $models.Settings): $CancellablePromise<void> {
    return $Call.ByID(708204809, settings);
}

export function ScanDirectory(dirPath: string, multi: boolean): $CancellablePromise<qrengine$0.BatchScanResult> {
    return $Call.ByID(1949796327, dirPath, multi).then(($result: any) => {
        return $$createType8($result);
    });
}

export function SetCompletionHandler(fn: any): $CancellablePromise<void> {
    return $Call.ByID(3495199423, fn);
}

export function SetPinned(id: string, pinned: boolean): $CancellablePromise<void> {
    return $Call.ByID(1933071185, id, pinned);
}

export function SetSaveDialog(fn: any): $CancellablePromise<void> {
    return $Call.ByID(2825278498, fn);
}

export function SetWorkerPayload(payload: string): $CancellablePromise<void> {
    return $Call.ByID(1044368277, payload);
}

export function UpsertPreset(preset: $models.Preset): $CancellablePromise<$models.Preset[]> {
    return $Call.ByID(293017653, preset).then(($result: any) => {
        return $$createType4($result);
    });
}

export function ValidateStyle(opts: qrengine$0.EncodeOptions): $CancellablePromise<string[]> {
    return $Call.ByID(2061329088, opts).then(($result: any) => {
        return $$createType5($result);
    });
}

// Private type creation functions
const $$createType0 = $models.HistoryEntry.createFrom;
const $$createType1 = qrengine$0.SafetyAssessment.createFrom;
const $$createType2 = qrengine$0.ScanResponse.createFrom;
const $$createType3 = $models.Preset.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $Create.Array($Create.Any);
const $$createType6 = $models.Settings.createFrom;
const $$createType7 = $Create.Array($$createType0);
const $$createType8 = qrengine$0.BatchScanResult.createFrom;
