// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "/wails/runtime.js";

export class BatchScanResult {
    "total_files_scanned": number;
    "successful_decodes": number;
    "duration_ms": number;
    "entries": ScanResponse[];

    /** Creates a new BatchScanResult instance. */
    constructor($$source: Partial<BatchScanResult> = {}) {
        if (!("total_files_scanned" in $$source)) {
            this["total_files_scanned"] = 0;
        }
        if (!("successful_decodes" in $$source)) {
            this["successful_decodes"] = 0;
        }
        if (!("duration_ms" in $$source)) {
            this["duration_ms"] = 0;
        }
        if (!("entries" in $$source)) {
            this["entries"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BatchScanResult instance from a string or object.
     */
    static createFrom($$source: any = {}): BatchScanResult {
        const $$createField3_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("entries" in $$parsedSource) {
            $$parsedSource["entries"] = $$createField3_0($$parsedSource["entries"]);
        }
        return new BatchScanResult($$parsedSource as Partial<BatchScanResult>);
    }
}

export class BoundingBox {
    "top_left": number[];
    "top_right": number[];
    "bottom_left": number[];
    "bottom_right"?: number[];

    /** Creates a new BoundingBox instance. */
    constructor($$source: Partial<BoundingBox> = {}) {
        if (!("top_left" in $$source)) {
            this["top_left"] = Array.from({ length: 2 }, () => 0);
        }
        if (!("top_right" in $$source)) {
            this["top_right"] = Array.from({ length: 2 }, () => 0);
        }
        if (!("bottom_left" in $$source)) {
            this["bottom_left"] = Array.from({ length: 2 }, () => 0);
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BoundingBox instance from a string or object.
     */
    static createFrom($$source: any = {}): BoundingBox {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BoundingBox($$parsedSource as Partial<BoundingBox>);
    }
}

export class BuildContentRequest {
    "type": ContentType;
    "fields": { [_ in string]?: string };

    /** Creates a new BuildContentRequest instance. */
    constructor($$source: Partial<BuildContentRequest> = {}) {
        if (!("type" in $$source)) {
            this["type"] = ContentType.$zero;
        }
        if (!("fields" in $$source)) {
            this["fields"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BuildContentRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): BuildContentRequest {
        const $$createField1_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("fields" in $$parsedSource) {
            $$parsedSource["fields"] = $$createField1_0($$parsedSource["fields"]);
        }
        return new BuildContentRequest($$parsedSource as Partial<BuildContentRequest>);
    }
}

export enum ContentType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    TypeText = "text",
    TypeURL = "url",
    TypeWiFi = "wifi",
    TypeEmail = "email",
    TypeSMS = "sms",
    TypePhone = "phone",
    TypeVCard = "vcard",
    TypeGeo = "geo",
    TypeEvent = "event",
    TypeSocial = "social",
};

export class DecodeResult {
    "content": string;
    "content_type": ContentType;
    "format": string;
    "error_correction_level": string;
    "bounding_box": BoundingBox;
    "security"?: SafetyAssessment | null;

    /** Creates a new DecodeResult instance. */
    constructor($$source: Partial<DecodeResult> = {}) {
        if (!("content" in $$source)) {
            this["content"] = "";
        }
        if (!("content_type" in $$source)) {
            this["content_type"] = ContentType.$zero;
        }
        if (!("format" in $$source)) {
            this["format"] = "";
        }
        if (!("error_correction_level" in $$source)) {
            this["error_correction_level"] = "";
        }
        if (!("bounding_box" in $$source)) {
            this["bounding_box"] = (new BoundingBox());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DecodeResult instance from a string or object.
     */
    static createFrom($$source: any = {}): DecodeResult {
        const $$createField4_0 = $$createType3;
        const $$createField5_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("bounding_box" in $$parsedSource) {
            $$parsedSource["bounding_box"] = $$createField4_0($$parsedSource["bounding_box"]);
        }
        if ("security" in $$parsedSource) {
            $$parsedSource["security"] = $$createField5_0($$parsedSource["security"]);
        }
        return new DecodeResult($$parsedSource as Partial<DecodeResult>);
    }
}

export class EncodeOptions {
    "content": string;
    "type"?: ContentType;
    "size": number;
    "ecc": string;
    "fg_color": string;
    "bg_color": string;
    "shape": string;
    "logo_b64"?: string;
    "format": string;
    "quiet_zone": number;

    /** Creates a new EncodeOptions instance. */
    constructor($$source: Partial<EncodeOptions> = {}) {
        if (!("content" in $$source)) {
            this["content"] = "";
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }
        if (!("ecc" in $$source)) {
            this["ecc"] = "";
        }
        if (!("fg_color" in $$source)) {
            this["fg_color"] = "";
        }
        if (!("bg_color" in $$source)) {
            this["bg_color"] = "";
        }
        if (!("shape" in $$source)) {
            this["shape"] = "";
        }
        if (!("format" in $$source)) {
            this["format"] = "";
        }
        if (!("quiet_zone" in $$source)) {
            this["quiet_zone"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EncodeOptions instance from a string or object.
     */
    static createFrom($$source: any = {}): EncodeOptions {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new EncodeOptions($$parsedSource as Partial<EncodeOptions>);
    }
}

export class SafetyAssessment {
    "is_suspicious": boolean;
    "score": number;
    "reasons": string[];
    "resolved_host": string;
    "is_shortener": boolean;

    /** Creates a new SafetyAssessment instance. */
    constructor($$source: Partial<SafetyAssessment> = {}) {
        if (!("is_suspicious" in $$source)) {
            this["is_suspicious"] = false;
        }
        if (!("score" in $$source)) {
            this["score"] = 0;
        }
        if (!("reasons" in $$source)) {
            this["reasons"] = [];
        }
        if (!("resolved_host" in $$source)) {
            this["resolved_host"] = "";
        }
        if (!("is_shortener" in $$source)) {
            this["is_shortener"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SafetyAssessment instance from a string or object.
     */
    static createFrom($$source: any = {}): SafetyAssessment {
        const $$createField2_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("reasons" in $$parsedSource) {
            $$parsedSource["reasons"] = $$createField2_0($$parsedSource["reasons"]);
        }
        return new SafetyAssessment($$parsedSource as Partial<SafetyAssessment>);
    }
}

export class ScanResponse {
    "success": boolean;
    "source_file"?: string;
    "scanned_at": string;
    "results": DecodeResult[];
    "error"?: string;

    /** Creates a new ScanResponse instance. */
    constructor($$source: Partial<ScanResponse> = {}) {
        if (!("success" in $$source)) {
            this["success"] = false;
        }
        if (!("scanned_at" in $$source)) {
            this["scanned_at"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("results" in $$source)) {
            this["results"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ScanResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): ScanResponse {
        const $$createField3_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("results" in $$parsedSource) {
            $$parsedSource["results"] = $$createField3_0($$parsedSource["results"]);
        }
        return new ScanResponse($$parsedSource as Partial<ScanResponse>);
    }
}

// Private type creation functions
const $$createType0 = ScanResponse.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Map($Create.Any, $Create.Any);
const $$createType3 = BoundingBox.createFrom;
const $$createType4 = SafetyAssessment.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = $Create.Array($Create.Any);
const $$createType7 = DecodeResult.createFrom;
const $$createType8 = $Create.Array($$createType7);
